[package]
name = "stacklet"
version = "0.1.0"
edition = "2021"
description = "Generate custom applets and menus"
repository = "https://github.com/ggemre/stacklet"
license = "MIT"

[dependencies]
pancurses = "0.17"
regex = "1.5"
fork = "0.1.22"
